- hosts: master
  become: yes
  tasks:

    - name: install Pod network
      become: yes
      become_user: root
      shell: |
              kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
              kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
      args:
        chdir: $HOME
